<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\S2ModKit.Adapters.Source2\S2ModKit.Adapters.Source2.csproj" />
    <ProjectReference Include="..\..\src\S2ModKit.Adapters.Vpk\S2ModKit.Adapters.Vpk.csproj" />
    <ProjectReference Include="..\..\src\S2ModKit.Application\S2ModKit.Application.csproj" />
    <ProjectReference Include="..\..\src\S2ModKit.Domain\S2ModKit.Domain.csproj" />
    <ProjectReference Include="..\..\src\S2ModKit.Geometry\S2ModKit.Geometry.csproj" />
    <ProjectReference Include="..\..\src\S2ModKit.Infrastructure\S2ModKit.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\S2ModKit.Reporting\S2ModKit.Reporting.csproj" />
  </ItemGroup>
</Project>
