<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="NJsonSchema" Version="11.6.1" />
    <PackageVersion Include="System.CommandLine" Version="2.0.2" />
    <PackageVersion Include="ValvePak" Version="5.0.2.177" />
    <PackageVersion Include="ValveResourceFormat" Version="20.0.6980" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>
</Project>
